export const initialSkillsData = [
  { key: "anthro", base: 1 },
  { key: "archaeology", base: 1 },
  { key: "art", base: 5 },
  { key: "fast_talk", base: 5 },
  { key: "library", base: 20 },
  { key: "charm", base: 15 },
  { key: "brawl", base: 25 },
  { key: "handgun", base: 20 },
  { key: "rifle", base: 25 },
  { key: "accounting", base: 5 },
  { key: "drive", base: 20 },
  { key: "heavy", base: 1 },
  { key: "credit", base: 0 },
  { key: "locksmith", base: 1 },
  { key: "stealth", base: 20 },
  { key: "law", base: 5 },
  { key: "listen", base: 20 },
  { key: "electric", base: 10 },
  { key: "electronics", base: 1 },
  { key: "dodge", base: "DEX/2", id: "skill-Dodge" },
  { key: "appraise", base: 5 },
  { key: "climb", base: 20 },
  { key: "history", base: 5 },
  { key: "disguise", base: 5 },
  { key: "computers", base: 5 },
  { key: "intimidate", base: 15 },
  { key: "throw", base: 20 },
  { key: "mother_tongue", base: "EDU", id: "skill-MotherTongue" },
  { key: "mech", base: 10 },
  { key: "medicine", base: 1 },
  { key: "cthulhu", base: 0 },
  { key: "swim", base: 20 },
  { key: "nature", base: 10 },
  { key: "occult", base: 5 },
  { key: "navigate", base: 10 },
  { key: "persuade", base: 10 },
  { key: "sleight", base: 10 },
  { key: "pilot", base: 1 },
  { key: "track", base: 10 },
  { key: "first_aid", base: 30 },
  { key: "psychoanalysis", base: 1 },
  { key: "psychology", base: 10 },
  { key: "jump", base: 20 },
  { key: "science", base: 1 },
  { key: "survival", base: 10 },
  { key: "spot", base: 25 },
];
