import type { Skill } from "../types";

// prettier-ignore
export const initialSkillsData: Skill[] = [
  { type: "standard", key: "anthro", base: 1, current: 1, checked: false, id: "skill-anthro" },
  { type: "standard", key: "archaeology", base: 1, current: 1, checked: false, id: "skill-archaeology" },
  { type: "static", key: "art", base: 5, id: "skill-art" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-art-0" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-art-1" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-art-2" },
  { type: "standard", key: "fast_talk", base: 5, current: 5, checked: false, id: "skill-fast_talk" },
  { type: "standard", key: "library", base: 20, current: 20, checked: false, id: "skill-library" },
  { type: "standard", key: "charm", base: 15, current: 15, checked: false, id: "skill-charm" },
  { type: "static", key: "ranged_combat", base: 0, id: "skill-ranged_combat" },
  { type: "standard", key: "handgun", base: 20, current: 20, checked: false, id: "skill-handgun" },
  { type: "standard", key: "rifle", base: 25, current: 25, checked: false, id: "skill-rifle" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-ranged_combat-0" },
  { type: "static", key: "close_combat", base: 0, id: "skill-close_combat" },
  { type: "standard", key: "brawl", base: 25, current: 25, checked: false, id: "skill-brawl" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-close_combat-0" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-close_combat-1" },
  { type: "standard", key: "accounting", base: 5, current: 5, checked: false, id: "skill-accounting" },
  { type: "standard", key: "drive", base: 20, current: 20, checked: false, id: "skill-drive" },
  { type: "standard", key: "heavy", base: 1, current: 1, checked: false, id: "skill-heavy" },
  { type: "standard", key: "credit", base: 0, current: -1, checked: false, id: "skill-credit" },
  { type: "standard", key: "locksmith", base: 1, current: 1, checked: false, id: "skill-locksmith" },
  { type: "standard", key: "stealth", base: 20, current: 20, checked: false, id: "skill-stealth" },
  { type: "standard", key: "law", base: 5, current: 5, checked: false, id: "skill-law" },
  { type: "standard", key: "listen", base: 20, current: 20, checked: false, id: "skill-listen" },
  { type: "standard", key: "electric", base: 10, current: 10, checked: false, id: "skill-electric" },
  { type: "standard", key: "electronics", base: 1, current: 1, checked: false, id: "skill-electronics" },
  { type: "standard", key: "dodge", base: "DEX/2", current: -1, checked: false, id: "skill-Dodge" },
  { type: "standard", key: "appraise", base: 5, current: 5, checked: false, id: "skill-appraise" },
  { type: "standard", key: "climb", base: 20, current: 20, checked: false, id: "skill-climb" },
  { type: "standard", key: "history", base: 5, current: 5, checked: false, id: "skill-history" },
  { type: "standard", key: "disguise", base: 5, current: 5, checked: false, id: "skill-disguise" },
  { type: "standard", key: "computers", base: 5, current: 5, checked: false, id: "skill-computers" },
  { type: "standard", key: "intimidate", base: 15, current: 15, checked: false, id: "skill-intimidate" },
  { type: "standard", key: "throw", base: 20, current: 20, checked: false, id: "skill-throw" },
  { type: "static", key: "mother_tongue", base: "EDU", id: "skill-MotherTongue" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-mother_tongue-0" },
  { type: "static", key: "languages", base: 1, id: "skill-language" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-language-0" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-language-1" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-language-2" },

  { type: "standard", key: "mech", base: 10, current: 10, checked: false, id: "skill-mech" },
  { type: "standard", key: "medicine", base: 1, current: 1, checked: false, id: "skill-medicine" },
  { type: "standard", key: "cthulhu", base: 0, current: 0, checked: false, id: "skill-cthulhu" },
  { type: "standard", key: "swim", base: 20, current: 20, checked: false, id: "skill-swim" },
  { type: "standard", key: "nature", base: 10, current: 10, checked: false, id: "skill-nature" },
  { type: "standard", key: "occult", base: 5, current: 5, checked: false, id: "skill-occult" },
  { type: "standard", key: "navigate", base: 10, current: 10, checked: false, id: "skill-navigate" },
  { type: "standard", key: "persuade", base: 10, current: 10, checked: false, id: "skill-persuade" },
  { type: "standard", key: "sleight", base: 10, current: 10, checked: false, id: "skill-sleight" },
  { type: "static", key: "pilot", base: 1, id: "skill-pilot" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-pilot-0" },
  { type: "standard", key: "track", base: 10, current: 10, checked: false, id: "skill-track" },
  { type: "standard", key: "first_aid", base: 30, current: 30, checked: false, id: "skill-first_aid" },
  { type: "standard", key: "psychoanalysis", base: 1, current: 1, checked: false, id: "skill-psychoanalysis" },
  { type: "standard", key: "psychology", base: 10, current: 10, checked: false, id: "skill-psychology" },
  { type: "standard", key: "jump", base: 20, current: 20, checked: false, id: "skill-jump" },
  { type: "static", key: "science", base: 1, id: "skill-science" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-science-0" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-science-1" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-science-2" },
  { type: "static", key: "survival", base: 10, id: "skill-survival" },
  { type: "custom", name: "", current: -1, checked: false, id: "skill-survival-0" },
  { type: "standard", key: "spot", base: 25, current: 25, checked: false, id: "skill-spot" },
  // Custom skills
  { type: "custom", name: "", current: -1, checked: false, id: "custom-0" },
  { type: "custom", name: "", current: -1, checked: false, id: "custom-1" },
  { type: "custom", name: "", current: -1, checked: false, id: "custom-2" },
  { type: "custom", name: "", current: -1, checked: false, id: "custom-3" },
  { type: "custom", name: "", current: -1, checked: false, id: "custom-4" },
];
